version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/twitter/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Paris"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"
